# Generated by Django 2.1.5 on 2019-01-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jyot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jyot.Signin'),
        ),
        migrations.AddField(
            model_name='materials',
            name='category',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='materials',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jyot.Dropdown'),
        ),
        migrations.AddField(
            model_name='materials',
            name='sub_category',
            field=models.TextField(default=None),
        ),
    ]
